// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (u User) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(u.Login) > 64 {
		errors[Columns.User.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.Password) > 64 {
		errors[Columns.User.Password] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.AuthKey) > 32 {
		errors[Columns.User.AuthKey] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (i Issue) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(i.IssueType) > 32 {
		errors[Columns.Issue.IssueType] = ErrMaxLength
	}

	if utf8.RuneCountInString(i.Title) > 255 {
		errors[Columns.Issue.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(i.Severity) > 16 {
		errors[Columns.Issue.Severity] = ErrMaxLength
	}

	if utf8.RuneCountInString(i.File) > 255 {
		errors[Columns.Issue.File] = ErrMaxLength
	}

	if utf8.RuneCountInString(i.Lines) > 255 {
		errors[Columns.Issue.Lines] = ErrMaxLength
	}

	if i.Comment != nil && utf8.RuneCountInString(*i.Comment) > 255 {
		errors[Columns.Issue.Comment] = ErrMaxLength
	}

	if i.LocalID != nil && utf8.RuneCountInString(*i.LocalID) > 16 {
		errors[Columns.Issue.LocalID] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (rf ReviewFile) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(rf.ReviewType) > 64 {
		errors[Columns.ReviewFile.ReviewType] = ErrMaxLength
	}

	if utf8.RuneCountInString(rf.TrafficLight) > 32 {
		errors[Columns.ReviewFile.TrafficLight] = ErrMaxLength
	}

	if utf8.RuneCountInString(rf.Summary) > 2048 {
		errors[Columns.ReviewFile.Summary] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (r Review) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(r.Title) > 255 {
		errors[Columns.Review.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.Description) > 2048 {
		errors[Columns.Review.Description] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.ExternalID) > 32 {
		errors[Columns.Review.ExternalID] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.TrafficLight) > 32 {
		errors[Columns.Review.TrafficLight] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.CommitHash) > 40 {
		errors[Columns.Review.CommitHash] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.SourceBranch) > 255 {
		errors[Columns.Review.SourceBranch] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.TargetBranch) > 255 {
		errors[Columns.Review.TargetBranch] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.Author) > 255 {
		errors[Columns.Review.Author] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (p Project) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(p.Title) > 255 {
		errors[Columns.Project.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(p.VcsURL) > 255 {
		errors[Columns.Project.VcsURL] = ErrMaxLength
	}

	if utf8.RuneCountInString(p.Language) > 32 {
		errors[Columns.Project.Language] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (p Prompt) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(p.Title) > 255 {
		errors[Columns.Prompt.Title] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (sc SlackChannel) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(sc.Title) > 255 {
		errors[Columns.SlackChannel.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(sc.Channel) > 255 {
		errors[Columns.SlackChannel.Channel] = ErrMaxLength
	}

	if utf8.RuneCountInString(sc.WebhookURL) > 1024 {
		errors[Columns.SlackChannel.WebhookURL] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (tt TaskTracker) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(tt.Title) > 255 {
		errors[Columns.TaskTracker.Title] = ErrMaxLength
	}

	if tt.AuthToken != nil && utf8.RuneCountInString(*tt.AuthToken) > 255 {
		errors[Columns.TaskTracker.AuthToken] = ErrMaxLength
	}

	if utf8.RuneCountInString(tt.URL) > 255 {
		errors[Columns.TaskTracker.URL] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
