// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}
	Issue struct {
		ID, ReviewFileID, IssueType, ReviewID, Title, Severity, Description, Content, File, Lines, Comment, IsFalsePositive, ProcessedAt, CreatedAt, UserID, StatusID, LocalID string

		ReviewFile, Review, User string
	}
	ReviewFile struct {
		ID, ReviewID, ReviewType, Content, IssueStats, TrafficLight, CreatedAt, Summary, IsAccepted, StatusID string

		Review string
	}
	Review struct {
		ID, ProjectID, Title, Description, ExternalID, TrafficLight, CommitHash, SourceBranch, TargetBranch, Author, CreatedAt, DurationMS, ModelInfo, StatusID, PromptID string

		Project, Prompt string
	}
	Project struct {
		ID, Title, VcsURL, Language, ProjectKey, PromptID, TaskTrackerID, SlackChannelID, CreatedAt, StatusID, Instructions string

		Prompt, TaskTracker, SlackChannel string
	}
	Prompt struct {
		ID, Title, Common, Architecture, Code, Security, Tests, CreatedAt, StatusID string
	}
	SlackChannel struct {
		ID, Title, Channel, WebhookURL, StatusID string
	}
	TaskTracker struct {
		ID, Title, AuthToken, FetchPrompt, CreatedAt, StatusID, URL string
	}
}{
	User: struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		CreatedAt:      "createdAt",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	Issue: struct {
		ID, ReviewFileID, IssueType, ReviewID, Title, Severity, Description, Content, File, Lines, Comment, IsFalsePositive, ProcessedAt, CreatedAt, UserID, StatusID, LocalID string

		ReviewFile, Review, User string
	}{
		ID:              "issueId",
		ReviewFileID:    "reviewFileId",
		IssueType:       "issueType",
		ReviewID:        "reviewId",
		Title:           "title",
		Severity:        "severity",
		Description:     "description",
		Content:         "content",
		File:            "file",
		Lines:           "lines",
		Comment:         "comment",
		IsFalsePositive: "isFalsePositive",
		ProcessedAt:     "processedAt",
		CreatedAt:       "createdAt",
		UserID:          "userId",
		StatusID:        "statusId",
		LocalID:         "localId",

		ReviewFile: "ReviewFile",
		Review:     "Review",
		User:       "User",
	},
	ReviewFile: struct {
		ID, ReviewID, ReviewType, Content, IssueStats, TrafficLight, CreatedAt, Summary, IsAccepted, StatusID string

		Review string
	}{
		ID:           "reviewFileId",
		ReviewID:     "reviewId",
		ReviewType:   "reviewType",
		Content:      "content",
		IssueStats:   "issueStats",
		TrafficLight: "trafficLight",
		CreatedAt:    "createdAt",
		Summary:      "summary",
		IsAccepted:   "isAccepted",
		StatusID:     "statusId",

		Review: "Review",
	},
	Review: struct {
		ID, ProjectID, Title, Description, ExternalID, TrafficLight, CommitHash, SourceBranch, TargetBranch, Author, CreatedAt, DurationMS, ModelInfo, StatusID, PromptID string

		Project, Prompt string
	}{
		ID:           "reviewId",
		ProjectID:    "projectId",
		Title:        "title",
		Description:  "description",
		ExternalID:   "externalId",
		TrafficLight: "trafficLight",
		CommitHash:   "commitHash",
		SourceBranch: "sourceBranch",
		TargetBranch: "targetBranch",
		Author:       "author",
		CreatedAt:    "createdAt",
		DurationMS:   "durationMS",
		ModelInfo:    "modelInfo",
		StatusID:     "statusId",
		PromptID:     "promptId",

		Project: "Project",
		Prompt:  "Prompt",
	},
	Project: struct {
		ID, Title, VcsURL, Language, ProjectKey, PromptID, TaskTrackerID, SlackChannelID, CreatedAt, StatusID, Instructions string

		Prompt, TaskTracker, SlackChannel string
	}{
		ID:             "projectId",
		Title:          "title",
		VcsURL:         "vcsURL",
		Language:       "language",
		ProjectKey:     "projectKey",
		PromptID:       "promptId",
		TaskTrackerID:  "taskTrackerId",
		SlackChannelID: "slackChannelId",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",
		Instructions:   "instructions",

		Prompt:       "Prompt",
		TaskTracker:  "TaskTracker",
		SlackChannel: "SlackChannel",
	},
	Prompt: struct {
		ID, Title, Common, Architecture, Code, Security, Tests, CreatedAt, StatusID string
	}{
		ID:           "promptId",
		Title:        "title",
		Common:       "common",
		Architecture: "architecture",
		Code:         "code",
		Security:     "security",
		Tests:        "tests",
		CreatedAt:    "createdAt",
		StatusID:     "statusId",
	},
	SlackChannel: struct {
		ID, Title, Channel, WebhookURL, StatusID string
	}{
		ID:         "slackChannelId",
		Title:      "title",
		Channel:    "channel",
		WebhookURL: "webhookURL",
		StatusID:   "statusId",
	},
	TaskTracker: struct {
		ID, Title, AuthToken, FetchPrompt, CreatedAt, StatusID, URL string
	}{
		ID:          "taskTrackerId",
		Title:       "title",
		AuthToken:   "authToken",
		FetchPrompt: "fetchPrompt",
		CreatedAt:   "createdAt",
		StatusID:    "statusId",
		URL:         "url",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	Issue struct {
		Name, Alias string
	}
	ReviewFile struct {
		Name, Alias string
	}
	Review struct {
		Name, Alias string
	}
	Project struct {
		Name, Alias string
	}
	Prompt struct {
		Name, Alias string
	}
	SlackChannel struct {
		Name, Alias string
	}
	TaskTracker struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	Issue: struct {
		Name, Alias string
	}{
		Name:  "issues",
		Alias: "t",
	},
	ReviewFile: struct {
		Name, Alias string
	}{
		Name:  "reviewFiles",
		Alias: "t",
	},
	Review: struct {
		Name, Alias string
	}{
		Name:  "reviews",
		Alias: "t",
	},
	Project: struct {
		Name, Alias string
	}{
		Name:  "projects",
		Alias: "t",
	},
	Prompt: struct {
		Name, Alias string
	}{
		Name:  "prompts",
		Alias: "t",
	},
	SlackChannel: struct {
		Name, Alias string
	}{
		Name:  "slackChannels",
		Alias: "t",
	},
	TaskTracker: struct {
		Name, Alias string
	}{
		Name:  "taskTrackers",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type Issue struct {
	tableName struct{} `pg:"issues,alias:t,discard_unknown_columns"`

	ID              int        `pg:"issueId,pk"`
	ReviewFileID    int        `pg:"reviewFileId,use_zero"`
	IssueType       string     `pg:"issueType,use_zero"`
	ReviewID        int        `pg:"reviewId,use_zero"`
	Title           string     `pg:"title,use_zero"`
	Severity        string     `pg:"severity,use_zero"`
	Description     string     `pg:"description,use_zero"`
	Content         string     `pg:"content,use_zero"`
	File            string     `pg:"file,use_zero"`
	Lines           string     `pg:"lines,use_zero"`
	Comment         *string    `pg:"comment"`
	IsFalsePositive *bool      `pg:"isFalsePositive"`
	ProcessedAt     *time.Time `pg:"processedAt"`
	CreatedAt       time.Time  `pg:"createdAt,use_zero"`
	UserID          *int       `pg:"userId"`
	StatusID        int        `pg:"statusId,use_zero"`
	LocalID         *string    `pg:"localId"`

	ReviewFile *ReviewFile `pg:"fk:reviewFileId,rel:has-one"`
	Review     *Review     `pg:"fk:reviewId,rel:has-one"`
	User       *User       `pg:"fk:userId,rel:has-one"`
}

type ReviewFile struct {
	tableName struct{} `pg:"reviewFiles,alias:t,discard_unknown_columns"`

	ID           int                  `pg:"reviewFileId,pk"`
	ReviewID     int                  `pg:"reviewId,use_zero"`
	ReviewType   string               `pg:"reviewType,use_zero"`
	Content      string               `pg:"content,use_zero"`
	IssueStats   ReviewFileIssueStats `pg:"issueStats,use_zero"`
	TrafficLight string               `pg:"trafficLight,use_zero"`
	CreatedAt    time.Time            `pg:"createdAt,use_zero"`
	Summary      string               `pg:"summary,use_zero"`
	IsAccepted   bool                 `pg:"isAccepted,use_zero"`
	StatusID     int                  `pg:"statusId,use_zero"`

	Review *Review `pg:"fk:reviewId,rel:has-one"`
}

type Review struct {
	tableName struct{} `pg:"reviews,alias:t,discard_unknown_columns"`

	ID           int             `pg:"reviewId,pk"`
	ProjectID    int             `pg:"projectId,use_zero"`
	Title        string          `pg:"title,use_zero"`
	Description  string          `pg:"description,use_zero"`
	ExternalID   string          `pg:"externalId,use_zero"`
	TrafficLight string          `pg:"trafficLight,use_zero"`
	CommitHash   string          `pg:"commitHash,use_zero"`
	SourceBranch string          `pg:"sourceBranch,use_zero"`
	TargetBranch string          `pg:"targetBranch,use_zero"`
	Author       string          `pg:"author,use_zero"`
	CreatedAt    time.Time       `pg:"createdAt,use_zero"`
	DurationMS   int             `pg:"durationMS,use_zero"`
	ModelInfo    ReviewModelInfo `pg:"modelInfo,use_zero"`
	StatusID     int             `pg:"statusId,use_zero"`
	PromptID     int             `pg:"promptId,use_zero"`

	Project *Project `pg:"fk:projectId,rel:has-one"`
	Prompt  *Prompt  `pg:"fk:promptId,rel:has-one"`
}

type Project struct {
	tableName struct{} `pg:"projects,alias:t,discard_unknown_columns"`

	ID             int       `pg:"projectId,pk"`
	Title          string    `pg:"title,use_zero"`
	VcsURL         string    `pg:"vcsURL,use_zero"`
	Language       string    `pg:"language,use_zero"`
	ProjectKey     string    `pg:"projectKey,type:uuid,use_zero"`
	PromptID       int       `pg:"promptId,use_zero"`
	TaskTrackerID  *int      `pg:"taskTrackerId"`
	SlackChannelID *int      `pg:"slackChannelId"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`
	Instructions   *string   `pg:"instructions"`

	Prompt       *Prompt       `pg:"fk:promptId,rel:has-one"`
	TaskTracker  *TaskTracker  `pg:"fk:taskTrackerId,rel:has-one"`
	SlackChannel *SlackChannel `pg:"fk:slackChannelId,rel:has-one"`
}

type Prompt struct {
	tableName struct{} `pg:"prompts,alias:t,discard_unknown_columns"`

	ID           int       `pg:"promptId,pk"`
	Title        string    `pg:"title,use_zero"`
	Common       string    `pg:"common,use_zero"`
	Architecture string    `pg:"architecture,use_zero"`
	Code         string    `pg:"code,use_zero"`
	Security     string    `pg:"security,use_zero"`
	Tests        string    `pg:"tests,use_zero"`
	CreatedAt    time.Time `pg:"createdAt,use_zero"`
	StatusID     int       `pg:"statusId,use_zero"`
}

type SlackChannel struct {
	tableName struct{} `pg:"slackChannels,alias:t,discard_unknown_columns"`

	ID         int    `pg:"slackChannelId,pk"`
	Title      string `pg:"title,use_zero"`
	Channel    string `pg:"channel,use_zero"`
	WebhookURL string `pg:"webhookURL,use_zero"`
	StatusID   int    `pg:"statusId,use_zero"`
}

type TaskTracker struct {
	tableName struct{} `pg:"taskTrackers,alias:t,discard_unknown_columns"`

	ID          int       `pg:"taskTrackerId,pk"`
	Title       string    `pg:"title,use_zero"`
	AuthToken   *string   `pg:"authToken"`
	FetchPrompt string    `pg:"fetchPrompt,use_zero"`
	CreatedAt   time.Time `pg:"createdAt,use_zero"`
	StatusID    int       `pg:"statusId,use_zero"`
	URL         string    `pg:"url,use_zero"`
}
