CREATE TABLE "runnerProfiles" (
	"runnerProfileId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"runner" varchar(32) NOT NULL,
	"model" varchar(128),
	"effort" varchar(16),
	"apiProvider" varchar(32),
	"apiBaseURL" varchar(255),
	"token" varchar(255),
	"params" jsonb NOT NULL DEFAULT '{}',
	"isDefault" boolean NOT NULL DEFAULT false,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "runnerProfiles_pkey" PRIMARY KEY("runnerProfileId")
);

ALTER TABLE "runnerProfiles" ADD CONSTRAINT "Ref_runnerProfiles_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

CREATE INDEX "ix_runnerProfiles_statusId" ON "runnerProfiles" ("statusId");
-- Single default is enforced in code (RunnerProfileService.unsetCurrentDefault),
-- not by a partial unique index: soft-delete keeps isDefault set, which a DB
-- constraint would count as a live default and block setting any new one.

ALTER TABLE "projects" ADD COLUMN "runnerProfileId" integer;
ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_runnerProfiles" FOREIGN KEY ("runnerProfileId")
	REFERENCES "runnerProfiles"("runnerProfileId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;
CREATE INDEX "ix_projects_runnerProfileId" ON "projects" ("runnerProfileId");

ALTER TABLE "reviews" ADD COLUMN "runnerProfile" jsonb NOT NULL DEFAULT '{}';

-- Seed the single default profile (matches reviewctl's previous ResolveDefaults: claude/opus/xhigh).
INSERT INTO "runnerProfiles" ("title", "runner", "model", "effort", "isDefault", "statusId")
VALUES ('Default', 'claude', 'opus', 'xhigh', true, 1);
