// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package reviewctl

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	Service struct{ ReviewConfig, Prompt, FusionPrompt string }
}{
	Service: struct{ ReviewConfig, Prompt, FusionPrompt string }{
		ReviewConfig: "reviewconfig",
		Prompt:       "prompt",
		FusionPrompt: "fusionprompt",
	},
}

func (Service) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"ReviewConfig": {
				Description: `ReviewConfig resolves the multi-review panel for a project key: the primary
runner (pinned profile or default), the additional panel members
(runnerProfileIds) and the optional judge (judgeRunnerProfileId). Each config
includes the real token. A nil judge means single review via the primary.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectKey",
						Description: `project key (UUID)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `ReviewSetup`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "ReviewSetup",
					Properties: smd.PropertyList{
						{
							Name:     "primary",
							Optional: true,
							Ref:      "#/definitions/Config",
							Type:     smd.Object,
						},
						{
							Name: "panel",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/Config",
							},
						},
						{
							Name:     "judge",
							Optional: true,
							Ref:      "#/definitions/Config",
							Type:     smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"Config": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "runnerProfileId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "runner",
									Type: smd.String,
								},
								{
									Name: "model",
									Type: smd.String,
								},
								{
									Name: "effort",
									Type: smd.String,
								},
								{
									Name: "apiProvider",
									Type: smd.String,
								},
								{
									Name: "apiBaseURL",
									Type: smd.String,
								},
								{
									Name: "token",
									Type: smd.String,
								},
								{
									Name: "params",
									Ref:  "#/definitions/RunnerProfileParams",
									Type: smd.Object,
								},
							},
						},
						"RunnerProfileParams": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "allowDangerousPermissions",
									Type: smd.Boolean,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					400: "invalid project key",
					404: "no runner profile for project (and no default)",
					500: "internal error",
				},
			},
			"Prompt": {
				Description: `Prompt assembles and returns the review prompt for a project key.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectKey",
						Description: `project key (UUID)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `string`,
					Type:        smd.String,
				},
				Errors: map[int]string{
					400: "invalid project key",
					500: "internal error",
				},
			},
			"FusionPrompt": {
				Description: `FusionPrompt returns the built-in judge/synthesizer prompt for multi-review.
The algorithm is project-agnostic, so the same built-in is served for every
project; the projectKey is validated for a consistent contract with Prompt and
to leave room for a per-project override later.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectKey",
						Description: `project key (UUID)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `string`,
					Type:        smd.String,
				},
				Errors: map[int]string{
					400: "invalid project key",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s Service) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.Service.ReviewConfig:
		var args = struct {
			ProjectKey string `json:"projectKey"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectKey"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.ReviewConfig(ctx, args.ProjectKey))

	case RPC.Service.Prompt:
		var args = struct {
			ProjectKey string `json:"projectKey"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectKey"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Prompt(ctx, args.ProjectKey))

	case RPC.Service.FusionPrompt:
		var args = struct {
			ProjectKey string `json:"projectKey"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectKey"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.FusionPrompt(ctx, args.ProjectKey))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
