// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package reviewctl

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	Service struct{ ReviewConfig, Prompt string }
}{
	Service: struct{ ReviewConfig, Prompt string }{
		ReviewConfig: "reviewconfig",
		Prompt:       "prompt",
	},
}

func (Service) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"ReviewConfig": {
				Description: `ReviewConfig resolves the runner profile for a project key — the project's pinned
profile or the default — and returns the run config including the real token.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectKey",
						Description: `project key (UUID)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Config`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Config",
					Properties: smd.PropertyList{
						{
							Name: "runnerProfileId",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "runner",
							Type: smd.String,
						},
						{
							Name: "model",
							Type: smd.String,
						},
						{
							Name: "effort",
							Type: smd.String,
						},
						{
							Name: "apiProvider",
							Type: smd.String,
						},
						{
							Name: "apiBaseURL",
							Type: smd.String,
						},
						{
							Name: "token",
							Type: smd.String,
						},
						{
							Name: "params",
							Ref:  "#/definitions/RunnerProfileParams",
							Type: smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"RunnerProfileParams": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "allowDangerousPermissions",
									Type: smd.Boolean,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					400: "invalid project key",
					404: "no runner profile for project (and no default)",
					500: "internal error",
				},
			},
			"Prompt": {
				Description: `Prompt assembles and returns the review prompt for a project key.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectKey",
						Description: `project key (UUID)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `string`,
					Type:        smd.String,
				},
				Errors: map[int]string{
					400: "invalid project key",
					500: "internal error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s Service) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.Service.ReviewConfig:
		var args = struct {
			ProjectKey string `json:"projectKey"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectKey"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.ReviewConfig(ctx, args.ProjectKey))

	case RPC.Service.Prompt:
		var args = struct {
			ProjectKey string `json:"projectKey"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectKey"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Prompt(ctx, args.ProjectKey))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
