// Code generated by colgen v0.1.2; DO NOT EDIT.
package rpc

import (
	"reviewsrv/pkg/reviewer"
)

func newIssues(in []reviewer.Issue) []Issue { return reviewer.MapP(in, newIssue) }

func newProjects(in []reviewer.Project) []Project { return reviewer.MapP(in, newProject) }

func newReviews(in []reviewer.Review) []Review { return reviewer.MapP(in, newReview) }

func newReviewFiles(in []reviewer.ReviewFile) []ReviewFile { return reviewer.MapP(in, newReviewFile) }

func newReviewSummaries(in []reviewer.Review) []ReviewSummary {
	return reviewer.MapP(in, newReviewSummary)
}
