// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	AppService    struct{ Version string }
	ReviewService struct{ Projects, ProjectByID, Get, Count, GetByID, Issues, CountIssues, IssuesByProject, CountIssuesByProject, Feedback, SetComment string }
}{
	AppService: struct{ Version string }{
		Version: "version",
	},
	ReviewService: struct{ Projects, ProjectByID, Get, Count, GetByID, Issues, CountIssues, IssuesByProject, CountIssuesByProject, Feedback, SetComment string }{
		Projects:             "projects",
		ProjectByID:          "projectbyid",
		Get:                  "get",
		Count:                "count",
		GetByID:              "getbyid",
		Issues:               "issues",
		CountIssues:          "countissues",
		IssuesByProject:      "issuesbyproject",
		CountIssuesByProject: "countissuesbyproject",
		Feedback:             "feedback",
		SetComment:           "setcomment",
	},
}

func (AppService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Version": {
				Description: `Version returns application version.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `string`,
					Type:        smd.String,
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s AppService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}

	switch method {
	case RPC.AppService.Version:
		resp.Set(s.Version())

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (ReviewService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Projects": {
				Description: `Projects returns list of all projects with review stats.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]Project",
					Items: map[string]string{
						"$ref": "#/definitions/Project",
					},
					Definitions: map[string]smd.Definition{
						"Project": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "projectId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "vcsURL",
									Type: smd.String,
								},
								{
									Name:     "taskTrackerURL",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "language",
									Type: smd.String,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
								{
									Name: "reviewCount",
									Type: smd.Integer,
								},
								{
									Name:     "lastReview",
									Optional: true,
									Ref:      "#/definitions/LastReview",
									Type:     smd.Object,
								},
							},
						},
						"LastReview": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "createdAt",
									Type: smd.String,
								},
								{
									Name: "author",
									Type: smd.String,
								},
								{
									Name: "trafficLight",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
			"ProjectByID": {
				Description: `ProjectByID returns a single project by ID.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectId",
						Description: `Project ID`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Project`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Project",
					Properties: smd.PropertyList{
						{
							Name: "projectId",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "vcsURL",
							Type: smd.String,
						},
						{
							Name:     "taskTrackerURL",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "language",
							Type: smd.String,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
						{
							Name: "reviewCount",
							Type: smd.Integer,
						},
						{
							Name:     "lastReview",
							Optional: true,
							Ref:      "#/definitions/LastReview",
							Type:     smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"LastReview": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "createdAt",
									Type: smd.String,
								},
								{
									Name: "author",
									Type: smd.String,
								},
								{
									Name: "trafficLight",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
					404: "Not Found",
				},
			},
			"Get": {
				Description: `Get returns list of reviews for a project.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectId",
						Description: `Project ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "filters",
						Optional:    true,
						Description: `Review filters`,
						Type:        smd.Object,
						TypeName:    "ReviewFilters",
						Properties: smd.PropertyList{
							{
								Name:     "author",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "trafficLight",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
					{
						Name:        "fromReviewId",
						Optional:    true,
						Description: `Cursor for infinite scroll pagination`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]ReviewSummary",
					Items: map[string]string{
						"$ref": "#/definitions/ReviewSummary",
					},
					Definitions: map[string]smd.Definition{
						"ReviewSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "reviewId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "externalId",
									Type: smd.String,
								},
								{
									Name: "trafficLight",
									Type: smd.String,
								},
								{
									Name: "author",
									Type: smd.String,
								},
								{
									Name: "sourceBranch",
									Type: smd.String,
								},
								{
									Name: "targetBranch",
									Type: smd.String,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
								{
									Name: "reviewFiles",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/ReviewFileSummary",
									},
								},
								{
									Name:     "lastVersionReviewId",
									Optional: true,
									Type:     smd.Integer,
								},
							},
						},
						"ReviewFileSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "reviewType",
									Type: smd.String,
								},
								{
									Name: "trafficLight",
									Type: smd.String,
								},
								{
									Name: "issueStats",
									Ref:  "#/definitions/IssueStats",
									Type: smd.Object,
								},
							},
						},
						"IssueStats": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "critical",
									Type: smd.Integer,
								},
								{
									Name: "high",
									Type: smd.Integer,
								},
								{
									Name: "medium",
									Type: smd.Integer,
								},
								{
									Name: "low",
									Type: smd.Integer,
								},
								{
									Name: "total",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
					404: "Not Found",
				},
			},
			"Count": {
				Description: `Count returns count of reviews for a project.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectId",
						Description: `Project ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "filters",
						Optional:    true,
						Description: `Review filters`,
						Type:        smd.Object,
						TypeName:    "ReviewFilters",
						Properties: smd.PropertyList{
							{
								Name:     "author",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "trafficLight",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `int`,
					Type:        smd.Integer,
				},
				Errors: map[int]string{
					500: "Internal Error",
					404: "Not Found",
				},
			},
			"GetByID": {
				Description: `GetByID returns full review details.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "reviewId",
						Description: `Review ID`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Review`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Review",
					Properties: smd.PropertyList{
						{
							Name: "reviewId",
							Type: smd.Integer,
						},
						{
							Name: "projectId",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name: "externalId",
							Type: smd.String,
						},
						{
							Name: "trafficLight",
							Type: smd.String,
						},
						{
							Name: "commitHash",
							Type: smd.String,
						},
						{
							Name: "sourceBranch",
							Type: smd.String,
						},
						{
							Name: "targetBranch",
							Type: smd.String,
						},
						{
							Name: "author",
							Type: smd.String,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
						{
							Name: "durationMs",
							Type: smd.Integer,
						},
						{
							Name: "modelInfo",
							Ref:  "#/definitions/ModelInfo",
							Type: smd.Object,
						},
						{
							Name: "reviewFiles",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/ReviewFile",
							},
						},
						{
							Name:     "lastVersionReviewId",
							Optional: true,
							Type:     smd.Integer,
						},
					},
					Definitions: map[string]smd.Definition{
						"ModelInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "model",
									Type: smd.String,
								},
								{
									Name: "inputTokens",
									Type: smd.Integer,
								},
								{
									Name: "outputTokens",
									Type: smd.Integer,
								},
								{
									Name: "costUsd",
									Type: smd.Float,
								},
							},
						},
						"ReviewFile": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "reviewFileId",
									Type: smd.Integer,
								},
								{
									Name: "reviewType",
									Type: smd.String,
								},
								{
									Name: "trafficLight",
									Type: smd.String,
								},
								{
									Name: "summary",
									Type: smd.String,
								},
								{
									Name: "isAccepted",
									Type: smd.Boolean,
								},
								{
									Name: "issueStats",
									Ref:  "#/definitions/IssueStats",
									Type: smd.Object,
								},
								{
									Name: "content",
									Type: smd.String,
								},
							},
						},
						"IssueStats": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "critical",
									Type: smd.Integer,
								},
								{
									Name: "high",
									Type: smd.Integer,
								},
								{
									Name: "medium",
									Type: smd.Integer,
								},
								{
									Name: "low",
									Type: smd.Integer,
								},
								{
									Name: "total",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
					404: "Not Found",
				},
			},
			"Issues": {
				Description: `Issues returns list of issues for a review.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "reviewId",
						Description: `Review ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "filters",
						Optional:    true,
						Description: `Issue filters`,
						Type:        smd.Object,
						TypeName:    "IssueFilters",
						Properties: smd.PropertyList{
							{
								Name:     "severity",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "issueType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "reviewType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "isFalsePositive",
								Optional: true,
								Type:     smd.Boolean,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]Issue`,
					Type:        smd.Array,
					TypeName:    "[]Issue",
					Items: map[string]string{
						"$ref": "#/definitions/Issue",
					},
					Definitions: map[string]smd.Definition{
						"Issue": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "issueId",
									Type: smd.Integer,
								},
								{
									Name: "reviewId",
									Type: smd.Integer,
								},
								{
									Name:     "localId",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "severity",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "content",
									Type: smd.String,
								},
								{
									Name: "file",
									Type: smd.String,
								},
								{
									Name: "lines",
									Type: smd.String,
								},
								{
									Name: "issueType",
									Type: smd.String,
								},
								{
									Name: "reviewType",
									Type: smd.String,
								},
								{
									Name: "commitHash",
									Type: smd.String,
								},
								{
									Name:     "isFalsePositive",
									Optional: true,
									Type:     smd.Boolean,
								},
								{
									Name:     "comment",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
			"CountIssues": {
				Description: `CountIssues returns count of issues for a review.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "reviewId",
						Description: `Review ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "filters",
						Optional:    true,
						Description: `Issue filters`,
						Type:        smd.Object,
						TypeName:    "IssueFilters",
						Properties: smd.PropertyList{
							{
								Name:     "severity",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "issueType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "reviewType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "isFalsePositive",
								Optional: true,
								Type:     smd.Boolean,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `int`,
					Type:        smd.Integer,
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
			"IssuesByProject": {
				Description: `IssuesByProject returns list of issues for a project with cursor-based pagination.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectId",
						Description: `Project ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "filters",
						Optional:    true,
						Description: `Issue filters (severity, issueType, reviewType, isFalsePositive)`,
						Type:        smd.Object,
						TypeName:    "IssueFilters",
						Properties: smd.PropertyList{
							{
								Name:     "severity",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "issueType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "reviewType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "isFalsePositive",
								Optional: true,
								Type:     smd.Boolean,
							},
						},
					},
					{
						Name:        "fromIssueId",
						Optional:    true,
						Description: `Cursor for infinite scroll pagination`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]Issue`,
					Type:        smd.Array,
					TypeName:    "[]Issue",
					Items: map[string]string{
						"$ref": "#/definitions/Issue",
					},
					Definitions: map[string]smd.Definition{
						"Issue": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "issueId",
									Type: smd.Integer,
								},
								{
									Name: "reviewId",
									Type: smd.Integer,
								},
								{
									Name:     "localId",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "severity",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "content",
									Type: smd.String,
								},
								{
									Name: "file",
									Type: smd.String,
								},
								{
									Name: "lines",
									Type: smd.String,
								},
								{
									Name: "issueType",
									Type: smd.String,
								},
								{
									Name: "reviewType",
									Type: smd.String,
								},
								{
									Name: "commitHash",
									Type: smd.String,
								},
								{
									Name:     "isFalsePositive",
									Optional: true,
									Type:     smd.Boolean,
								},
								{
									Name:     "comment",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
					404: "Not Found",
				},
			},
			"CountIssuesByProject": {
				Description: `CountIssuesByProject returns count of issues for a project.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "projectId",
						Description: `Project ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "filters",
						Optional:    true,
						Description: `Issue filters (severity, issueType, reviewType, isFalsePositive)`,
						Type:        smd.Object,
						TypeName:    "IssueFilters",
						Properties: smd.PropertyList{
							{
								Name:     "severity",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "issueType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "reviewType",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name:     "isFalsePositive",
								Optional: true,
								Type:     smd.Boolean,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `int`,
					Type:        smd.Integer,
				},
				Errors: map[int]string{
					500: "Internal Error",
					404: "Not Found",
				},
			},
			"Feedback": {
				Description: `Feedback updates false positive flag for an issue.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "issueId",
						Description: `Issue ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "isFalsePositive",
						Optional:    true,
						Description: `False positive flag (true = false positive, false = confirmed, null = unprocessed)`,
						Type:        smd.Boolean,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"SetComment": {
				Description: `SetComment updates comment for an issue.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "issueId",
						Description: `Issue ID`,
						Type:        smd.Integer,
					},
					{
						Name:        "comment",
						Optional:    true,
						Description: `Developer comment (max 255 chars, null to clear)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					400: "Bad Request",
					404: "Not Found",
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s ReviewService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.ReviewService.Projects:
		resp.Set(s.Projects(ctx))

	case RPC.ReviewService.ProjectByID:
		var args = struct {
			ProjectId int `json:"projectId"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectId"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.ProjectByID(ctx, args.ProjectId))

	case RPC.ReviewService.Get:
		var args = struct {
			ProjectId    int            `json:"projectId"`
			Filters      *ReviewFilters `json:"filters"`
			FromReviewId *int           `json:"fromReviewId"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectId", "filters", "fromReviewId"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Get(ctx, args.ProjectId, args.Filters, args.FromReviewId))

	case RPC.ReviewService.Count:
		var args = struct {
			ProjectId int            `json:"projectId"`
			Filters   *ReviewFilters `json:"filters"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectId", "filters"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Count(ctx, args.ProjectId, args.Filters))

	case RPC.ReviewService.GetByID:
		var args = struct {
			ReviewId int `json:"reviewId"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"reviewId"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetByID(ctx, args.ReviewId))

	case RPC.ReviewService.Issues:
		var args = struct {
			ReviewId int           `json:"reviewId"`
			Filters  *IssueFilters `json:"filters"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"reviewId", "filters"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Issues(ctx, args.ReviewId, args.Filters))

	case RPC.ReviewService.CountIssues:
		var args = struct {
			ReviewId int           `json:"reviewId"`
			Filters  *IssueFilters `json:"filters"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"reviewId", "filters"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.CountIssues(ctx, args.ReviewId, args.Filters))

	case RPC.ReviewService.IssuesByProject:
		var args = struct {
			ProjectId   int           `json:"projectId"`
			Filters     *IssueFilters `json:"filters"`
			FromIssueId *int          `json:"fromIssueId"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectId", "filters", "fromIssueId"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.IssuesByProject(ctx, args.ProjectId, args.Filters, args.FromIssueId))

	case RPC.ReviewService.CountIssuesByProject:
		var args = struct {
			ProjectId int           `json:"projectId"`
			Filters   *IssueFilters `json:"filters"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"projectId", "filters"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.CountIssuesByProject(ctx, args.ProjectId, args.Filters))

	case RPC.ReviewService.Feedback:
		var args = struct {
			IssueId         int   `json:"issueId"`
			IsFalsePositive *bool `json:"isFalsePositive"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"issueId", "isFalsePositive"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Feedback(ctx, args.IssueId, args.IsFalsePositive))

	case RPC.ReviewService.SetComment:
		var args = struct {
			IssueId int     `json:"issueId"`
			Comment *string `json:"comment"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"issueId", "comment"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.SetComment(ctx, args.IssueId, args.Comment))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
