// Code generated by colgen v0.1.2; DO NOT EDIT.
package reviewer

import (
	"reviewsrv/pkg/db"
)

type Issues []Issue

func (ll Issues) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Issues) Index() map[int]Issue {
	r := make(map[int]Issue, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewIssues(in []db.Issue) Issues { return MapP(in, NewIssue) }

func (ll Issues) GroupByReviewFileID() map[int]Issues {
	r := make(map[int]Issues, len(ll))
	for i := range ll {
		r[ll[i].ReviewFileID] = append(r[ll[i].ReviewFileID], ll[i])
	}
	return r
}

type Projects []Project

func (ll Projects) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Projects) Index() map[int]Project {
	r := make(map[int]Project, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewProjects(in []db.Project) Projects { return MapP(in, NewProject) }

type Reviews []Review

func (ll Reviews) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Reviews) Index() map[int]Review {
	r := make(map[int]Review, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewReviews(in []db.Review) Reviews { return MapP(in, NewReview) }

type ReviewFiles []ReviewFile

func (ll ReviewFiles) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll ReviewFiles) Index() map[int]ReviewFile {
	r := make(map[int]ReviewFile, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewReviewFiles(in []db.ReviewFile) ReviewFiles { return MapP(in, NewReviewFile) }

func (ll ReviewFiles) GroupByReviewID() map[int]ReviewFiles {
	r := make(map[int]ReviewFiles, len(ll))
	for i := range ll {
		r[ll[i].ReviewID] = append(r[ll[i].ReviewID], ll[i])
	}
	return r
}
