-- =============================================================================
-- Diagram Name: reviewsrv
-- Created on: 2/19/2026 12:58:43 PM
-- Diagram Version: 
-- =============================================================================


CREATE TABLE "prompts" (
	"promptId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"common" text NOT NULL,
	"architecture" text NOT NULL,
	"code" text NOT NULL,
	"security" text NOT NULL,
	"tests" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	PRIMARY KEY("promptId")
);

CREATE TABLE "statuses" (
	"statusId" int4 NOT NULL,
	"title" varchar(255) NOT NULL,
	"alias" varchar(64),
	PRIMARY KEY("statusId")
);

CREATE TABLE "taskTrackers" (
	"taskTrackerId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"url" varchar(255) NOT NULL,
	"authToken" varchar(255),
	"fetchPrompt" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	PRIMARY KEY("taskTrackerId")
);

CREATE TABLE "slackChannels" (
	"slackChannelId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"channel" varchar(255) NOT NULL,
	"webhookURL" varchar(1024) NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("slackChannelId")
);

CREATE TABLE "projects" (
	"projectId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"vcsURL" varchar(255) NOT NULL,
	"language" varchar(32) NOT NULL,
	"projectKey" uuid NOT NULL,
	"instructions" text,
	"promptId" int4 NOT NULL,
	"taskTrackerId" int4,
	"slackChannelId" int4,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	PRIMARY KEY("projectId"),
	CONSTRAINT "UNQ_projects_projectKey" UNIQUE("projectKey")
);

CREATE TABLE "reviews" (
	"reviewId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"projectId" int4 NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" varchar(2048) NOT NULL,
	"externalId" varchar(32) NOT NULL,
	"trafficLight" varchar(32) NOT NULL DEFAULT 'none',
	"commitHash" varchar(40) NOT NULL,
	"sourceBranch" varchar(255) NOT NULL,
	"targetBranch" varchar(255) NOT NULL,
	"author" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"durationMS" int4 NOT NULL DEFAULT 0,
	"modelInfo" jsonb NOT NULL DEFAULT '{}',
	"statusId" int4 NOT NULL,
	"promptId" int4 NOT NULL,
	PRIMARY KEY("reviewId")
);

CREATE INDEX "IX_reviews_projectId" ON "reviews" (
	"projectId"
);


CREATE INDEX "IX_reviews_externalId" ON "reviews" (
	"externalId"
);


CREATE TABLE "reviewFiles" (
	"reviewFileId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"reviewId" int4 NOT NULL,
	"reviewType" varchar(64) NOT NULL,
	"content" text NOT NULL,
	"issueStats" jsonb NOT NULL DEFAULT '{}',
	"trafficLight" varchar(32) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"summary" varchar(2048) NOT NULL,
	"isAccepted" bool NOT NULL DEFAULT False,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("reviewFileId")
);

CREATE INDEX "IX_reviews_reviewId" ON "reviewFiles" (
	"reviewId"
);


CREATE TABLE "issues" (
	"issueId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"reviewFileId" int4 NOT NULL,
	"issueType" varchar(32) NOT NULL,
	"reviewId" int4 NOT NULL,
	"title" varchar(255) NOT NULL,
	"severity" varchar(16) NOT NULL,
	"description" text NOT NULL,
	"content" text NOT NULL,
	"file" varchar(255) NOT NULL,
	"lines" varchar(255) NOT NULL,
	"comment" varchar(255),
	"localId" varchar(16),
	"isFalsePositive" bool,
	"processedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"userId" int4,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("issueId")
);

CREATE INDEX "IX_issues_isFalsePositive" ON "issues" (
	"isFalsePositive"
);


CREATE INDEX "IX_issues_reviewId" ON "issues" (
	"reviewId"
);


CREATE INDEX "IX_issues_reviewFileId" ON "issues" (
	"reviewFileId"
);


CREATE TABLE "users" (
	"userId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"login" varchar(64) NOT NULL,
	"password" varchar(64) NOT NULL,
	"authKey" varchar(32),
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"lastActivityAt" timestamp with time zone,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("userId")
);


ALTER TABLE "prompts" ADD CONSTRAINT "Ref_prompts_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "taskTrackers" ADD CONSTRAINT "Ref_taskTrackers_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "slackChannels" ADD CONSTRAINT "Ref_slackChannels_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_prompts" FOREIGN KEY ("promptId")
	REFERENCES "prompts"("promptId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_taskTrackers" FOREIGN KEY ("taskTrackerId")
	REFERENCES "taskTrackers"("taskTrackerId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_slackChannels" FOREIGN KEY ("slackChannelId")
	REFERENCES "slackChannels"("slackChannelId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "projects" ADD CONSTRAINT "Ref_projects_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_projects" FOREIGN KEY ("projectId")
	REFERENCES "projects"("projectId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_prompts" FOREIGN KEY ("promptId")
	REFERENCES "prompts"("promptId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviewFiles" ADD CONSTRAINT "Ref_reviewFiles_to_reviews" FOREIGN KEY ("reviewId")
	REFERENCES "reviews"("reviewId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "reviewFiles" ADD CONSTRAINT "Ref_reviewFiles_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_reviewFiles" FOREIGN KEY ("reviewFileId")
	REFERENCES "reviewFiles"("reviewFileId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_users" FOREIGN KEY ("userId")
	REFERENCES "users"("userId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "issues" ADD CONSTRAINT "Ref_issues_to_reviews" FOREIGN KEY ("reviewId")
	REFERENCES "reviews"("reviewId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "users" ADD CONSTRAINT "Ref_users_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;


